version: "3.3"

volumes:
  pgdata:

services:
  database:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8000:80"
    environment:
      AdminKey: ${AdminKey}
      DedicatedServerKeys: ${DedicatedServerKeys}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      StripeApiKey: ${StripeApiKey}
      StripeSignature: ${StripeSignature}
    restart: on-failure
    depends_on:
      - database
